### PR TITLE
better organization of structure, minor verifs and add js-cookie

### PR DESCRIPTION
**Pull request by SimonMfroy**
Change of structure for Admin and Member
yarn add js-cookie
Small verifs for routes admin/member

### CODE REVIEW

**Review by nlabrazi — COMMENTED** [review]
Looks good except for "cookies stuff" we are working on a solution to manage AUTH (Rails+React) @SimonMfroy

**Comment by SimonMfroy** [comment]
Outdated version.
Close.

**Comment by SimonMfroy** [comment]
New version of the feature : 
- structure of files created
- verif for routes
- redirection to login

**Comment by SimonMfroy** [comment]
Better redirection for non connected user and verif for non-member / non-admin.
redirection to login ok.
Good to merge.

**Review by HugoPeranSejourne — APPROVED** [review]

**Pull request merged**
